'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace E4425.Models

	Partial Public Class City
		Public Sub New()
			Me.Countries = New HashSet(Of Country)()
			Me.Customers = New HashSet(Of Customer)()
		End Sub

		Private privateCityId As Integer
		Public Property CityId() As Integer
			Get
				Return privateCityId
			End Get
			Set(ByVal value As Integer)
				privateCityId = value
			End Set
		End Property
		Private privateCityName As String
		Public Property CityName() As String
			Get
				Return privateCityName
			End Get
			Set(ByVal value As String)
				privateCityName = value
			End Set
		End Property
		Private privateCountryId? As Integer
		Public Property CountryId() As Integer?
			Get
				Return privateCountryId
			End Get
			Set(ByVal value? As Integer)
				privateCountryId = value
			End Set
		End Property

		Private privateCountry As Country
		Public Overridable Property Country() As Country
			Get
				Return privateCountry
			End Get
			Set(ByVal value As Country)
				privateCountry = value
			End Set
		End Property
		Private privateCountries As ICollection(Of Country)
		Public Overridable Property Countries() As ICollection(Of Country)
			Get
				Return privateCountries
			End Get
			Set(ByVal value As ICollection(Of Country))
				privateCountries = value
			End Set
		End Property
		Private privateCustomers As ICollection(Of Customer)
		Public Overridable Property Customers() As ICollection(Of Customer)
			Get
				Return privateCustomers
			End Get
			Set(ByVal value As ICollection(Of Customer))
				privateCustomers = value
			End Set
		End Property
	End Class
End Namespace
