'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Collections.Generic
Namespace E4425.Models

	Partial Public Class Customer
		Private privateCustomerId As Integer
		Public Property CustomerId() As Integer
			Get
				Return privateCustomerId
			End Get
			Set(ByVal value As Integer)
				privateCustomerId = value
			End Set
		End Property
		Private privateCustomerName As String
		Public Property CustomerName() As String
			Get
				Return privateCustomerName
			End Get
			Set(ByVal value As String)
				privateCustomerName = value
			End Set
		End Property
		Private privateCountryId? As Integer
		Public Property CountryId() As Integer?
			Get
				Return privateCountryId
			End Get
			Set(ByVal value? As Integer)
				privateCountryId = value
			End Set
		End Property
		Private privateCityId? As Integer
		Public Property CityId() As Integer?
			Get
				Return privateCityId
			End Get
			Set(ByVal value? As Integer)
				privateCityId = value
			End Set
		End Property

		Private privateCity As City
		Public Overridable Property City() As City
			Get
				Return privateCity
			End Get
			Set(ByVal value As City)
				privateCity = value
			End Set
		End Property
		Private privateCountry As Country
		Public Overridable Property Country() As Country
			Get
				Return privateCountry
			End Get
			Set(ByVal value As Country)
				privateCountry = value
			End Set
		End Property
	End Class
End Namespace
