'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Data.Entity
	Imports System.Data.Entity.Infrastructure
Namespace E4425.Models

	Partial Public Class WorldCitiesEntities
		Inherits DbContext
		Public Sub New()
			MyBase.New("name=WorldCitiesEntities")
		End Sub

		Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
			Throw New UnintentionalCodeFirstException()
		End Sub

		Private privateCities As DbSet(Of City)
		Public Property Cities() As DbSet(Of City)
			Get
				Return privateCities
			End Get
			Set(ByVal value As DbSet(Of City))
				privateCities = value
			End Set
		End Property
		Private privateCountries As DbSet(Of Country)
		Public Property Countries() As DbSet(Of Country)
			Get
				Return privateCountries
			End Get
			Set(ByVal value As DbSet(Of Country))
				privateCountries = value
			End Set
		End Property
		Private privateCustomers As DbSet(Of Customer)
		Public Property Customers() As DbSet(Of Customer)
			Get
				Return privateCustomers
			End Get
			Set(ByVal value As DbSet(Of Customer))
				privateCustomers = value
			End Set
		End Property
	End Class
End Namespace
